### ISSUE TITLE
Setup a CI pipeline

### ISSUE THREAD

**Issue by zeschg** [siemens/libuta#2]
Automate testing with a CI pipline.

**Comment by jan-kiszka** [comment]
In case you need inspirations:
- https://github.com/siemens/efibootguard (Travis-CI and also Coverity Scan)
- https://github.com/siemens/meta-iot2050/commit/bf8fda91a26daf67be2dcb1328b0fe88def0d563 (almost working attempt to use github workflows - only failed because we hit the runtime limit with that workload)
